name: Bug Report | Bug 反馈 | Fehler melden
description: Report a bug in 中文 / English / Deutsch
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        请选择一种语言填写：中文 / English / Deutsch。
        Please fill in one language only.
        Bitte nur eine Sprache ausfuellen.

  - type: dropdown
    id: language
    attributes:
      label: 语言 / Language / Sprache
      options:
        - 中文
        - English
        - Deutsch
    validations:
      required: true

  - type: checkboxes
    id: precheck
    attributes:
      label: 提交前确认 / Pre-check / Vor dem Senden
      options:
        - label: 我已搜索现有 Issue（非重复） / I searched existing issues / Ich habe bestehende Issues geprueft
          required: true

  - type: textarea
    id: bug_summary
    attributes:
      label: 问题描述 / Bug Summary / Kurzbeschreibung
      description: 一句话说清问题。Write one clear sentence. Beschreibe das Problem kurz.
      placeholder: 例如：启动后点击历史列表会闪退 / e.g. App crashes after clicking history
    validations:
      required: true

  - type: textarea
    id: reproduce_steps
    attributes:
      label: 复现步骤 / Steps to Reproduce / Schritte zur Reproduktion
      description: 按顺序写步骤。List ordered steps. Schritte bitte in Reihenfolge.
      placeholder: |
        1. 打开 Deck / Open Deck
        2. 点击... / Click...
        3. 出现... / Observe...
    validations:
      required: true

  - type: textarea
    id: actual_result
    attributes:
      label: 实际结果 / Actual Result / Tatsächliches Ergebnis
      placeholder: 实际发生了什么？What happened? Was ist passiert?
    validations:
      required: true

  - type: textarea
    id: expected_result
    attributes:
      label: 预期结果 / Expected Result / Erwartetes Ergebnis
      placeholder: 你希望发生什么？What should happen? Was sollte passieren?
    validations:
      required: true

  - type: input
    id: deck_version
    attributes:
      label: Deck 版本 / Deck Version / Deck-Version
      placeholder: e.g. 1.2.3
    validations:
      required: true

  - type: input
    id: macos_version
    attributes:
      label: macOS 版本 / macOS Version
      placeholder: e.g. macOS 15.3
    validations:
      required: true

  - type: dropdown
    id: chip
    attributes:
      label: 芯片类型 / Chip Type / Chip-Typ
      options:
        - Apple Silicon
        - Intel
        - Other / 其他 / Sonstiges
    validations:
      required: true

  - type: checkboxes
    id: install_method
    attributes:
      label: 安装方式（可多选）/ Install Method (multi-select) / Installationsart (Mehrfachauswahl)
      options:
        - label: 通过官网安装 / Installed from official website / Von der offiziellen Website installiert
        - label: 通过 GitHub 安装 / Installed from GitHub / Ueber GitHub installiert
        - label: 通过软件内自动更新安装 / Installed via in-app auto update / Ueber In-App-Update installiert
        - label: 其他 / Other / Sonstiges

  - type: textarea
    id: screenshots
    attributes:
      label: 截图（可选）/ Screenshots (optional) / Screenshots (optional)
      description: 可直接拖拽图片。Drop images here if available.
      placeholder: 可以留空
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: 日志（可选）/ Logs (optional) / Logs (optional)
      description: 可在 Console.app 过滤 "Deck" 后粘贴日志。Paste logs if available.
      placeholder: 可以留空
    validations:
      required: false
